language: python

before_install:
  - pip install poetry

install:
  - pip install pip -U
  - pip install tox
  - poetry install -v

script:
  - tox

jobs:
  include:
    - python: "3.7"
      dist: xenial
